---
repos:
# Ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.8
  hooks:
  - id: ruff
    args: ["--fix"]
  - id: ruff-format
# https://pycqa.github.io/isort/docs/configuration/black_compatibility.html#integration-with-pre-commit
- repo: https://github.com/pycqa/isort
  rev: 7.0.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
# https://github.com/pre-commit/pre-commit-hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: check-json
  - id: check-toml
  - id: no-commit-to-branch
    args: [--branch=main]
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
# Gitup action
#- repo: https://github.com/rhysd/actionlint
#  rev: v1.7.9
#  hooks:
    #  - id: actionlint
# codespell
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: [
    "--write-changes",
    "--skip=*.json,*.bib,*.txt,*.cls,scripts/environment_vtscat_save.yml",
    "--ignore-words-list=livetime,fom,rsource,gaus,precess,forbit,nd,precessed,crate,parms,safty,sideral,ist,highe,functon,tre,ned,sourc,parm,fo,coo,miror",
    ]
    additional_dependencies:
      - tomli
#  - repo: https://github.com/Freed-Wu/mirrors-astyle
#    rev: v3.4.13
#    hooks:
#    -   id: astyle
#        args: [--options=./.astylerc]
#        files: '^.*\.(c|cpp|cxx|h|hpp|inc|C)$'
